### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Mirrorman95** [jasmyn/MaxHBO#1]
I just installed this on Firefox, and it's not making my HBO Max UI go away. The right-click menu doesn't even have it as an option.

**Comment by jazweatherhead** [comment]
HBO claim they fixed the bug that caused this issue in the first place. Does your seek bar not disappear when watching something? Just wanna be sure we're on the same page... 

If you're still getting that bug they may have altered things since I wrote the plugin, I haven't tested it in months as I don't get the bug anymore. If your bar doesn't disappear in full screen after a few seconds what OS are you on? If I can I'll try to test it.

**Comment by Mirrorman95** [comment]
It only doesn't disappear in full screen when I pause it. I was hoping to take a few quick screenshots without the UI elements getting in the way.

**Comment by jazweatherhead** [comment]
Ah, ok. It was meant to fix a bug where the seek bar wouldn't ever disappear, which HBO have since patched. It was hacked together in one night then posted to r/hbomax where people were bitching about this bug. Though that doesn't explain why you don't see the option when you right-click. This plugin is likely past its useful lifespan, though. I'll probably make it private so other people don't get the same impression you did. Maybe spamming the print screen key could act as a workaround for your actual problem. Good luck.
